### ISSUE TITLE
support for managing connection scripts

### ISSUE THREAD

**Issue by pklingem** [articulate/authoritah-js#1]
![image](https://cloud.githubusercontent.com/assets/46536/16158913/bd6ecdca-348d-11e6-96ae-68f35414a479.png)

Those are manageable via (deeply nested in the JSON object for a connection):

https://auth0.com/docs/api/management/v2#!/Connections/patch_connections_by_id

**Comment by plukevdh** [comment]
Available in > 0.3. Version 0.4 no longer deletes connections due to user data impact.
